[tool.poetry]
name = "wiki-js-mcp"
version = "1.0.0"
description = "Model Context Protocol (MCP) server for Wiki.js integration with hierarchical documentation support"
authors = ["Sahil Pethe <workpethesahil@proton.me>"]
license = "MIT"
readme = "README.md"
packages = [{include = "wiki_mcp_server.py", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
fastmcp = "^0.1.0"
httpx = "^0.27.0"
pydantic = "^2.0"
pydantic-settings = "^2.0"
python-slugify = "^8.0"
markdown = "^3.5"
beautifulsoup4 = "^4.12"
python-dotenv = "^1.0.0"
sqlalchemy = "^2.0"
tenacity = "^8.0"
aiosqlite = "^0.19.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
black = "^23.0.0"
isort = "^5.12.0"
mypy = "^1.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
wikijs-mcp = "wiki_mcp_server:main"

[tool.black]
line-length = 88
target-version = ['py312']

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true 